Add a missing cast for fconst_2
Fixes

```
java.lang.IllegalArgumentException: Unexpected opcode: 13
	at codes.rafael.asmjdkbridge.JdkClassWriter$WritingMethodVisitor.visitInsn(JdkClassWriter.java:813)
	at net.bytebuddy.jar.asm.MethodVisitor.visitInsn(MethodVisitor.java:337)
```