Update JdkClassWriter.java
```
RoundTrip of asm-test-9.7-sources\jdk3\AllInstructions.class via ClassNode was unsuccessful
    java.lang.IllegalArgumentException: Unexpected opcode: 13
```
Add missing FCONST_2 opcode.